# Generated by Django 4.2.10 on 2024-04-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(blank=True, max_length=225, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('rmse_predict', models.IntegerField(default=0)),
                ('mae_predict', models.IntegerField(default=0)),
                ('mape_predict', models.IntegerField(default=0)),
                ('mase_predict', models.IntegerField(default=0)),
                ('mse_arima', models.IntegerField(default=0)),
                ('rmse_arima', models.IntegerField(default=0)),
                ('mae_arima', models.IntegerField(default=0)),
                ('mape_arima', models.IntegerField(default=0)),
                ('mase_arima', models.IntegerField(default=0)),
            ],
        ),
    ]
