# Generated by Django 4.2.10 on 2024-04-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='batch_size',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='predict',
            name='epochs',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='predict',
            name='windows_size',
            field=models.IntegerField(default=24),
        ),
    ]
